### PR TITLE
[#PRDGROWTH-271] adding product lists to admin serializer

### PR DESCRIPTION
**Pull request by ganeshmohan2021**

### CODE REVIEW

**Comment by ganeshmohan2021** [comment]
> @ganeshmohan2021 These updates will need to be made to the Rails 6 branch also

Sure Tom

**Comment by bcasci** [comment]
@ganeshmohan2021 Can you please get the test suite to pass? Once that's done we will need to release a new version of the gem, and then adjust the other apps as needed, but we can sync up on that wen the time comes

**Comment by hoenth** [comment]
You'll want to release both a new 5.2 and 6.1 version

**Comment by ganeshmohan2021** [comment]
> @ganeshmohan2021 Can you please get the test suite to pass? Once that's done we will need to release a new version of the gem, and then adjust the other apps as needed, but we can sync up on that wen the time comes

Hi @bcasci , The spec failure is related to ruby version. In my local all spec is passing. I don't know how to fix the bundler issue in Circle CI?

**Comment by tmking** [comment]
> > @ganeshmohan2021 Can you please get the test suite to pass? Once that's done we will need to release a new version of the gem, and then adjust the other apps as needed, but we can sync up on that wen the time comes
> 
> Hi @bcasci , The spec failure is related to ruby version. In my local all spec is passing. I don't know how to fix the bundler issue in Circle CI?

@ganeshmohan2021 you can set the bundler version in `.circleci/config` on line 36.

**Comment by bcasci** [comment]
@tmking @ganeshmohan2021 I resolved it by changing the CircleCI image. It was old.

**Review by bcasci — APPROVED** [review]

**Pull request merged**
